openapi: 3.0.3
info:
  title: prices-api
  version: 1.0.0
  description: API para consultar precios de productos por marca y rango de fechas.

servers:
  - url: http://localhost:8080

paths:
  /api/prices:
    get:
      summary: Consultar precio de un producto por marca y rango de fechas
      operationId: getPrice
      parameters:
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: ID de la marca
        - name: productId
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: ID del producto
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: Fecha/hora de aplicación
      responses:
        '200':
          description: Precio encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Price"
        '404':
          description: No se encontró precio para los parámetros indicados
        '400':
          description: Parámetros de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    Price:
      type: object
      properties:
        id:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        value:
          type: number
          format: double
          description: Valor monetario del precio
      required:
        - id
        - brandId
        - productId
        - start
        - end
        - value

    ApiError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
